### ISSUE TITLE
Todo revisão

### ISSUE THREAD

**Issue by devgiordane** [devgiordane/todo#1]
- [ ] Arezza Brizotto
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Giovanna Furlani
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Mariana Patriota
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Victoria Mezêncio
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Jacqueline Souza
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Patricia Murai
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Amanda Cuello
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Ana Paula Figueiredo
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Anny Caroline
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Camilla Genial
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Denise Sgaetti
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Juliane Souza
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Lisandra Gândara
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Michele da Silva
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Raquel Moraes
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Renata Almeida
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Soraya Daniela Lira
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Suzi Guedes
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Carol molina - campinas
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Carol molina - jaguariuna
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Erica Rodrigues
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] P. Palazzo - Moema
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] P. Palazzo - Barueri
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Débora Paes
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] amanda - chapadinha
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Daiane Bandeira
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Retiely
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Poliana Conradi
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
- [ ] Giuliana
    - [ ] Organizar pasta videos (Nomear corretamente pastas e videos finalizados)
    - [ ] Anotar tarefas de edição se houver
    - [ ] Criar campanha já editadas que não foram ao ar
    - [ ] Atualizar gastos no painel revisão
    - [ ] Atualizar status das campanhas no painel visão geral
    - [ ] Enviar campanhas conforme disponiveis no painel e no plano
    - [ ] Revisar as campanhas que já estão no ar (Gasto, cliques, Frequencia)
    - [ ] Ler e interagir no grupo, e anotar o que foi reclamado nos ultimos dias
    - [ ] Olhar se há tarefas relacionadas no todo
